/* eslint-env mocha */
'use strict'

// tests for authenticate
// Generated by serverless-mocha-plugin

const mochaPlugin = require('serverless-mocha-plugin')
const dirtyChai = require('dirty-chai')
mochaPlugin.chai.use(dirtyChai)
const expect = mochaPlugin.chai.expect
let wrapped = mochaPlugin.getWrapper('authenticate', '../../../src/functions/authenticate.js', 'authenticate')
let AWS = require('aws-sdk-mock')
let AWS_SDK = require('aws-sdk')
AWS.setSDKInstance(AWS_SDK)

describe('authenticate', () => {
  before((done) => {
    done()
  })

  it('implement tests here', () => {
    AWS.mock('DynamoDB.DocumentClient', 'query', (params) => {
      return new Promise((resolve, reject) => {
        resolve({
          Items: [{
            username: 'ausername',
            password: 'apassword'
          }]
        })
      })
    })
    return wrapped.run({
      body: JSON.stringify({
        username: 'ausername',
        password: 'apassword'
      })
    }).then((response) => {
      console.log('response', response)
      expect(response).to.not.be.empty()
    })
  })
})
